### DISCUSSION TITLE
Store HCD parameters in summary IDS

### DISCUSSION THREAD

**Discussion by prasad-sawantdesai** [iterorganization/IMAS-Data-Dictionary#64] [Q&A]
For scenario files we store HCD parameters for different sources. Should we store these values as part of structure `heating_and_current_drive` in summary IDS?
`/work/imas/shared/imasdb/ITER/3/0/ids_1341740117.yaml`
```
hcd:
    p_hcd: 20.0
    p_ec:  20.0
    p_ic:  0.00
    p_nbi: 0.00
    p_lh:  0.00
```

and each source is calculate like below
```python
        n_ec = len(summary.heating_current_drive.ec)
        if n_ec > 0:
            for isource in range(n_ec):
                if len(summary.heating_current_drive.ec[isource].power.value) > 0:
                    p_ec = p_ec + max(summary.heating_current_drive.ec[isource].power.value) * 1.0e-6
```
