### DISCUSSION TITLE
placeholder for scenario_key_parameters

### DISCUSSION THREAD

**Discussion by prasad-sawantdesai** [iterorganization/IMAS-Data-Dictionary#66] [Q&A] [answered]
Below values are calculated from time based array. These scaler values show important characteristics, Should we have placeholder to store these in `summary` IDS?

```
scenario_key_parameters:
    confinement_regime: L-mode
    magnetic_field: -5.39
    main_species: H
    plasma_current: -5.00 
    central_electron_density: tbd
    central_zeff: tbd
    density_peaking: tbd
    sepmid_electron_density: 1.67e+19
    sepmid_zeff: 1.00
```
